name: Deploy AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read  # Required to check out the repository

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Prepare deployment package
        run: |
          mkdir -p ./dist
          pip install -r requirements.txt -t ./dist/
          cp src/lambda_function.py ./dist/
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::292967571313:role/GitHubActionRole
          aws-region: us-east-1
          
      - name: Deploy Lambda Function
        run: |
          # Check if function exists
          if aws lambda get-function --function-name my-lambda-function >/dev/null 2>&1; then
            echo "Function exists, updating code..."
            cd ./dist && zip -r ../lambda-function.zip .
            aws lambda update-function-code \
              --function-name my-lambda-function \
              --zip-file fileb://../lambda-function.zip
          else
            echo "Creating new function..."
            cd ./dist && zip -r ../lambda-function.zip .
            aws lambda create-function \
              --function-name my-lambda-function \
              --runtime python3.11 \
              --role arn:aws:iam::292967571313:role/LambdaExecutionRole \
              --handler lambda_function.lambda_handler \
              --zip-file fileb://../lambda-function.zip
          fi